# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute log10 prior of model configuration
#' @param mcfg A vector of model configuration
#' @param pi_vec A vector of prior probabilities
#' @return Result Log 10 prior of model configuration
#' @export
compute_log10_prior <- function(mcfg, pi_vec) {
    .Call(`_dap_compute_log10_prior`, mcfg, pi_vec)
}

#' Compute log10 posterior scores for multiple model configurations
#' @param X An n*p matrix of genotype data
#' @param y An n-vector of phenotype data
#' @param cmfg_matrix An m*p matrix of model configurations
#' @param pi_vec A vector of prior probabilities
#' @param phi2_vec A vector of phi2 values
#' @return An m-vector of log10 posterior scores
#' @export
compute_log10_posterior <- function(X, y, cmfg_matrix, pi_vec, phi2_vec) {
    .Call(`_dap_compute_log10_posterior`, X, y, cmfg_matrix, pi_vec, phi2_vec)
}

#' Implementation of DAP-PIR algorithm in C++
#' 
#' Performs fine mapping using DAP-PIR algorithm
#'
#' @param X Genotype matrix
#' @param y Phenotype vector
#' @param L Number of causal variants
#' @param matrix Proposal density matrix from SuSiE
#' @param threshold Threshold for proposal density
#' @param prior_weights Vector of prior probabilities
#' @param phi2_vec Vector of scaled prior effect size variances
#' @param r2_threshold Threshold for LD
#' @param coverage Coverage for credible set
#'
#' @return A list containing:
#' \itemize{
#'   \item model_config - Model configurations
#'   \item posterior_prob - Posterior probabilities
#'   \item log10_posterior_score - Log10 posterior scores
#'   \item log10_nc - Log10 normalizing constant
#'   \item pip - Posterior inclusion probabilities
#' }
#' @export
dap_main <- function(X, y, L, matrix, threshold, prior_weights, phi2_vec, r2_threshold, coverage) {
    .Call(`_dap_dap_main`, X, y, L, matrix, threshold, prior_weights, phi2_vec, r2_threshold, coverage)
}

#' Find all model combinations that have a proposal density greater than or equal to a threshold
#' @param mat A p x L matrix of proposal densities from SuSiE
#' @param threshold The threshold value of the proposal density
#' @return A NumericMatrix containing the unique combinations
#' @export
pir <- function(mat, threshold) {
    .Call(`_dap_pir`, mat, threshold)
}

#' Compute R-squared between two vectors
#' 
#' @param X NumericMatrix containing the vectors
#' @param i Index of first vector
#' @param j Index of second vector
#' @return Double containing R-squared value
#' @noRd
NULL

#' Compute median of a sorted vector
#' @name median
#' @param v Vector of sorted values
#' @return Median value
#' @noRd
NULL

#' Get signal clusters or credible sets at given coverage level
#' 
#' This function identifies clusters of correlated signals based on R-squared values
#' and model posterior probabilities.
#' 
#' @param X NumericMatrix containing the raw data
#' @param mat NumericMatrix containing the alpha matrix
#' @param cmfg_mat NumericMatrix containing the CMFG matrix
#' @param posterior_probs NumericVector of posterior probabilities
#' @param col_names CharacterVector of column names
#' @param r2_threshold Double specifying the R-squared threshold for correlation
#' @param coverage Double specifying the coverage threshold
#' @return List containing:
#'   \item{clusters}{List of character vectors containing cluster memberships}
#'   \item{spip}{Numeric vector of signal posterior inclusion probabilities}
#'   \item{sizes}{Integer vector of cluster sizes}
#'   \item{r2_threshold}{Double containing the R-squared threshold used}
#'   \item{coverage}{Double containing the coverage threshold used}
#' @export
get_sc <- function(X, mat, cmfg_mat, posterior_probs, col_names, r2_threshold, coverage) {
    .Call(`_dap_get_sc`, X, mat, cmfg_mat, posterior_probs, col_names, r2_threshold, coverage)
}

